UPDATE `quest_template` SET `OfferRewardText`='William sent you? Bless his soul. I... I''m ok... It''s just... Well...' WHERE `Id`=26150;
UPDATE `quest_template` SET `OfferRewardText`='Ah!  I can''t stand us being apart.  I have to see her!!' WHERE `Id`=106;
UPDATE `quest_template` SET `OfferRewardText`='Thank goodness!  That pig was getting so big she''d have eaten our whole crop!  Thank you, $N.$B$BNow, do any of these suit you?' WHERE `Id`=88;
UPDATE `quest_template` SET `OfferRewardText`='You lost a what?  Well I didn''t take no necklace, because I ain''t no thief!$B$BI might know who did but...<grin>...I''m too hungry to remember.' WHERE `Id`=85;
UPDATE `quest_template` SET `OfferRewardText`='Thanks, $N!  And come back if you want to trade again.' WHERE `Id`=16;
UPDATE `quest_template` SET `OfferRewardText`='Though this wild boar meat is bland, simmer it enough in the right spices and it sure does make for some tasty pie!' WHERE `Id`=86;
UPDATE `quest_template` SET `OfferRewardText`='My heart goes out to those two poor souls, Maybell and Tommy Joe.  I remember being young and in love, once.$B$BThere must be something I can do to help them!  Let me think...' WHERE `Id`=107;
UPDATE `quest_template` SET `OfferRewardText`='You got them.  Good show!  Now, just one moment while I concoct the potion...' WHERE `Id`=112;
UPDATE `quest_template` SET `OfferRewardText`='Mm, yum!  This pie is the best!$B$BI think my memory is coming back to me...' WHERE `Id`=84;
UPDATE `quest_template` SET `OfferRewardText`='Oh...my!  I feel guilty deceiving my family, but my feelings for Tommy Joe are too strong to ignore.$B$BThank you, $N.  I''ll drink this liquor as soon as I have the chance and sneak away to my love.$B$BAnd for you... please take this.' WHERE `Id`=114;
UPDATE `quest_template` SET `OfferRewardText`='Oh, you found it!  Thank you, thank you dear!$B$BHere, take this.  It was my husband''s and he always said it was lucky.  If only he didn''t forget it on his last campaign! *sniff*' WHERE `Id`=87;
UPDATE `quest_template` SET `OfferRewardText`='You''re here to help with my delivery?  Very good!' WHERE `Id`=1097;
UPDATE `quest_template` SET `OfferRewardText`='Ah, these are nice scraps, if a little rough...$B$BHere you are!' WHERE `Id`=83;
UPDATE `quest_template` SET `OfferRewardText`='Kobolds at the Jasperlode Mine, you say?  Curses!  The situation is worsening by the minute!$B$BThank you for the report, $N.  But I wish that the news you brought was good news.' WHERE `Id`=76;
UPDATE `quest_template` SET `OfferRewardText`='You find around the neck of the corpse a metal medallion inscribed with the words: \"Footman Rolf Hartford.\"' WHERE `Id`=45;
UPDATE `quest_template` SET `OfferRewardText`='Excellent! Thanks to you, I should be able to complete the order in time. To show my gratitude, I would like to offer some coin as compensation for your troubles.$B$BThank you and farewell.' WHERE `Id`=5545;
UPDATE `quest_template` SET `OfferRewardText`='And justice is served!' WHERE `Id`=26152;
UPDATE `quest_template` SET `OfferRewardText`='Hm... I have heard of this \"Collector\" but I don''t know whom he''s working for.  Thank you for the schedule.  It will help us solve this mystery.' WHERE `Id`=123;
UPDATE `quest_template` SET `OfferRewardText`='Marshall Dughan sent you, eh?  Well you''re not from the army, but if Dughan sent you then that''s good enough for me!$B$BOur situation is, to say the least, a stressed one.  I hope you can give us a hand.' WHERE `Id`=239;
UPDATE `quest_template` SET `OfferRewardText`='I see you''ve been busy!  You have our thanks, $N.' WHERE `Id`=11;
UPDATE `quest_template` SET `OfferRewardText`='This is useless. Look at the date on this letter. The Furlbrows have been squatting on the Jansen Steed for five years.$B$BThey never could quite get their wagon... fixed.' WHERE `Id`=184;
UPDATE `quest_template` SET `OfferRewardText`='Murder, rookie. That''s what you''re looking at on the ground in front of us.' WHERE `Id`=26378;
UPDATE `quest_template` SET `OfferRewardText`='You have confirmed my fears, $N.  The murlocs are a threat we cannot ignore.' WHERE `Id`=71;
UPDATE `quest_template` SET `OfferRewardText`='Ah, thank you for the marker.  Please feel free to pick your choice of armor.$B$BLuck to you, brave $c.  And may this armor serve you well.' WHERE `Id`=59;
UPDATE `quest_template` SET `OfferRewardText`='You have the fins?  Great!  Marshal Dughan is anxious about the Murloc situation in eastern Elwynn, and I''d like to tell him that it''s becoming under control.$B$BYour actions have helped realize that.' WHERE `Id`=46;
UPDATE `quest_template` SET `OfferRewardText`='Thanks a lot for the help, $N.  Something in the forest must be making these animals so bold.$B$BWhatever it is, I hope it stays there.' WHERE `Id`=52;
UPDATE `quest_template` SET `OfferRewardText`='Aha!  So Grimand finally finished my axe!  I can''t wait to try it against some troggs and kobolds!$B$BMany thanks, $N.  It was a long distance to travel for this delivery.   Here are some coins for your efforts.' WHERE `Id`=353;
UPDATE `quest_template` SET `OfferRewardText`='You found him?  Well done, $N.  He won''t be \"collecting\" from the Elwynn Mines again!$B$BAnd this ring you found is interesting... it''s a membership ring for the old Stonemason''s Guild in Stormwind. I haven''t seen one of these in years, since back in the days when the Defias Brotherhood used to infest this land.' WHERE `Id`=147;
UPDATE `quest_template` SET `OfferRewardText`='Ah, so you''ve seen Renato?  Well here you are, $gsir:ma''am;.  A bottle of our special pinot noir.  You''ll not find its equal in all of Azeroth!' WHERE `Id`=332;
UPDATE `quest_template` SET `OfferRewardText`='So you''ve been to the nests and placed the feathers of your prey within them. That took a fair portion of courage, no doubt about it.$B$BDo you feel a little tougher, $N? Because you look tougher now then when you first came here.  I guess the Barrens is doing its job.' WHERE `Id`=905;
UPDATE `quest_template` SET `OfferRewardText`='A disciple of the arcane always finds a way forward.  I''m glad to see you, $N.' WHERE `Id`=14277;
UPDATE `quest_template` SET `OfferRewardText`='You''ve learned with such speed and ease.  Soon you''ll be the one doing the teaching.' WHERE `Id`=14281;
UPDATE `quest_template` SET `OfferRewardText`='You''ve done well in coming here.  If we Gilneans stick together we might yet defeat this terrible enemy.' WHERE `Id`=14288;
UPDATE `quest_template` SET `OfferRewardText`='You did the impossible, $N.  You convinced Grandma Wahl to leave her home.$B$BYou are something else, let me tell you.' WHERE `Id`=14402;
UPDATE `quest_template` SET `OfferRewardText`='It says here that Harlan''s business is booming.  That''s good news, but I wonder why people have need of all that armor.  I''ve heard nothing of open war...is there something the nobles aren''t telling us?$B$BWell, thank you for bringing the request.  Here''s your payment, and I''ll see to it that Harlan gets his supplies.' WHERE `Id`=333;
UPDATE `quest_template` SET `OfferRewardText`='Oh, blast!  I thought forgetting my kit would free me from work.  Now I guess I''ll have to help the Larsons with their sewing...$B$BOh, well.  Fun will come later I guess.' WHERE `Id`=334;
UPDATE `quest_template` SET `OfferRewardText`='Those look like some nice bass, $N.  Let''s fry em'' up and see how they taste!' WHERE `Id`=26420;
UPDATE `quest_template` SET `OfferRewardText`='These sacks look like just enough, $N.  Can''t wait to see the smiles on the orphans'' faces.' WHERE `Id`=26192;
UPDATE `quest_template` SET `OfferRewardText`='Just smellin'' you comin'' got my stomach rumblin''! We''re gonna eat like kings tonight!' WHERE `Id`=26230;
UPDATE `quest_template` SET `OfferRewardText`='You''ve done it, $N! You''ve upturned the Searing Blade''s invasion before it could even start! Take this, as a token of my thanks.' WHERE `Id`=26856;
UPDATE `quest_template` SET `OfferRewardText`='My children will sing songs of your glories, $N!' WHERE `Id`=26858;
UPDATE `quest_template` SET `OfferRewardText`='Anotha newblood, eh?$B$BYa actually have a wild look about ya though. Fierce eyes. You might have the makings of a real $c.$B$BLets not waste anymore time ''den.' WHERE `Id`=24764;
UPDATE `quest_template` SET `OfferRewardText`='Not bad, mon. Ya have a natural flow to ya casts - you may have a talent for dis.$B$BSome rough edges ta be sure, but we''ll get dose ironed out here and I''ll teach ya a few new tings as we go.' WHERE `Id`=24765;
UPDATE `quest_template` SET `OfferRewardText`='Dese are some fine pelts, $G boy:girl;. We could make some hefty cloaks outta dese.' WHERE `Id`=24767;
UPDATE `quest_template` SET `OfferRewardText`='Ya handle yerself quite well. Ya gonna be quite powerful some day.' WHERE `Id`=24768;
UPDATE `quest_template` SET `OfferRewardText`='Good work, mon! Dis stuff come easy to ya.' WHERE `Id`=24766;
UPDATE `quest_template` SET `OfferRewardText`='Ya tha new recruit everyone''s talkin'' about, eh? Welcome ta tha Darkspear.' WHERE `Id`=24769;
UPDATE `quest_template` SET `OfferRewardText`='Nice ta see new faces ''round here, mon. It''s easy ta get ta feelin'' isolated since we left Orgrimmar.' WHERE `Id`=24622;
UPDATE `quest_template` SET `OfferRewardText`='Tha power d''at burst forth when tha Sea Witch died was immense. I can use d''is power ta enact a vision of places far away.$B$BObserve, youngblood. I want ya ta be here when I make contact wit'' Thrall, perhaps it will be grantin'' ya insight as well.' WHERE `Id`=24814;
UPDATE `quest_template` SET `OfferRewardText`='Welcome, young $r.$B$BYa come highly recommended, mon. It''s nice ta finally be meetin'' ya in person.' WHERE `Id`=25073;
UPDATE `quest_template` SET `OfferRewardText`='This is it!  The scorpid juju Bom''bay been waitin'' for!  Now we gonna fix you right up, $c.$b$bYou come back to Bom''bay when you be needin'' a pickup.  Bom''bay got the spells to fix ya!' WHERE `Id`=25165;
UPDATE `quest_template` SET `OfferRewardText`='You have to get this meat to Orgrimmar?  That is no problem.  For a small fee, my wind rider can take you there.' WHERE `Id`=6365;
UPDATE `quest_template` SET `OfferRewardText`='Oh, wonderful!  Those are fine cuts!  These are from Grimtak, are they?  That orc sure knows his way into a lady''s heart...$B$BOh, I can''t wait to cook it.  But not too much!  Meat is best served rare, don''t you think?' WHERE `Id`=6384;
UPDATE `quest_template` SET `OfferRewardText`='You have to get this to Razor Hill in Durotar?  Yes, I can get you there...' WHERE `Id`=6385;
UPDATE `quest_template` SET `OfferRewardText`='Hah!  I guess she liked it!  Nothing brings red to a lady''s cheeks like a big, juicy steak!$B$BThank you, $N.  You''ve done me a great service.  Here is some money for your trouble, and don''t be surprised if I invite you to my wedding!' WHERE `Id`=6386;
UPDATE `quest_template` SET `OfferRewardText`='A fresh recruit from Orgrimmar is it?$B$B<Kargal sizes you up.>$B$BI''ll take what I can get. Keeping the roads open has been a nightmare.' WHERE `Id`=26642;
UPDATE `quest_template` SET `OfferRewardText`='You''ve beaten Echeyakee, and though his days of hunting are over... his spirit is with you. He will show you the strength found in subtlety, and the honor in mercy.$B$BI underestimated you, $c. The Horde is fortunate to have you in its ranks.' WHERE `Id`=881;
UPDATE `quest_template` SET `OfferRewardText`='I see you''ve left a string of corpses in your wake, $r. I couldn''t have done better. The livestock may be lost, but the land remains ours - thank you!' WHERE `Id`=13973;
UPDATE `quest_template` SET `OfferRewardText`='Oh my. We want to question this quilboar, not tenderize him!' WHERE `Id`=13961;
UPDATE `quest_template` SET `OfferRewardText`='Very interesting - our brute here seems both enthralled and terrified of the one they call \"Tortusk.\" A powerful leader can inspire his people to acts of greatness or atrocity... but we orcs would know that more than others.$B$BWe should turn our attention to this Tortusk problem.' WHERE `Id`=13963;
UPDATE `quest_template` SET `OfferRewardText`='Ah, so Tortusk behaved as I expected? Went right for your throat? It is good that he''s dead.$B$BThe Razormane quilboar have been separated from their leadership in the southern Barrens, no doubt allowing an animal like him to come to power. Perhaps without his influence we can start a dialogue with the survivors... Although hotter heads may prevail. ' WHERE `Id`=13968;
UPDATE `quest_template` SET `OfferRewardText`='This poor battered kodo looks to be on the verge of death, but is still breathing. The Razormane haven''t even plundered its cargo yet. If it can be revived, you may be able to save the entire shipment.' WHERE `Id`=13969;
UPDATE `quest_template` SET `OfferRewardText`='As you experience what Shadowglen has to teach you, come see me--I will be able to help you understand more about your role as a hunter and what you are capable of.$B$BThese are dangerous times, $N, do not take for granted the skill of your pets--there are things in this world more dangerous than you can imagine. Go with Elune and return to me again.' WHERE `Id`=3117;
UPDATE `quest_template` SET `OfferRewardText`='You are a quick study in our ways. I look forward to continuing your training in the future. Return to me when the time is right.' WHERE `Id`=26947;
UPDATE `quest_template` SET `OfferRewardText`='I am finally free of the control of the Gnarlpine. Thank you, $N.$B$BMy spirit may now rest peacefully forever in the Emerald Dream.$B$BPerhaps one day we may meet again, young $c. But, for now, please accept this reward as a symbol of my gratitude.' WHERE `Id`=2561;
UPDATE `quest_template` SET `OfferRewardText`='You got them. This is good! I''m hoping that careful study might lead me to understand where the timberling corruption stems from.$B$BI will plant these seeds in special soil I have prepared.  I believe the seeds will sprout into timberlings who are much more docile.$B$BPerhaps later you can see the results!' WHERE `Id`=918;
UPDATE `quest_template` SET `OfferRewardText`='That''s a lot!  I''m afraid they''re spreading at a dangerous rate.  I hope I can solve the riddle of what is tainting them.$B$BThank you for your help, $N.  The land is a cleaner place from your efforts.' WHERE `Id`=919;
UPDATE `quest_template` SET `OfferRewardText`='Along with the druids, the Oracle Tree has been carefully monitoring the growth of Teldrassil. Our observations have been disheartening, but all is not without hope.$B$BThe tree is indeed recovering since it''s blessing, but the growth is still somehow stunted... hindered.$B$BWe suspect some portion of the corruption remains within the tree, waiting to be cleansed. We simply need to find it.' WHERE `Id`=7383;
UPDATE `quest_template` SET `OfferRewardText`='So, the king has heard our plea? Thank Elune! We can use all the help we can get.' WHERE `Id`=28490;
UPDATE `quest_template` SET `OfferRewardText`='Yes, $c? What brings you to this place?' WHERE `Id`=26878;
UPDATE `quest_template` SET `OfferRewardText`='Well done, $N. Without Kreenig to orchestrate the raids, my grunts should be able to keep Far Watch secure. Your people should be proud to count you among them. ' WHERE `Id`=872;
UPDATE `quest_template` SET `OfferRewardText`='Haha! Thank you, $N! This will help us greatly. I''ll get these supplies packed up and on their way to the Crossroads immediately. ' WHERE `Id`=5041;
UPDATE `quest_template` SET `OfferRewardText`='You''re a sight, $r. That''s the first caravan to make it through this week!' WHERE `Id`=13949;
UPDATE `quest_template` SET `OfferRewardText`='It''s about time we got some supplies through here. It''s bad enough to be severed from Mulgore, but this city would fall apart if we lost our trade with Orgrimmar.' WHERE `Id`=13975;
UPDATE `quest_template` SET `OfferRewardText`='Thank ya so much! They can be vicious when provoked, but most of da time dey don''t know betta.' WHERE `Id`=24623;
UPDATE `quest_template` SET `OfferRewardText`='Thank you, $c.$B$BIt will be takin'' brave and determined people like you ta drive da Darkspear up again. I hope dere are more people even half as dedicated to come.' WHERE `Id`=24624;
UPDATE `quest_template` SET `OfferRewardText`='Well done, $n! Dis naga has set us back quite some time, but nothin'' will be holdin'' us down foreva.$B$BIt''s good ta be havin'' ya wit us, $n. Ya have a fierce heart within ya.' WHERE `Id`=24625;
UPDATE `quest_template` SET `OfferRewardText`='Swiftclaw! Kijara was tellin'' me about him and he sounded like he''d be a handful. I don''t mind da challenge - it''s da spirited ones like dat that be makin'' da bravest and truest companions when real times of need be comin''.$B$BTank ya, hon. Ya''ve been very helpful.' WHERE `Id`=24626;
UPDATE `quest_template` SET `OfferRewardText`='Good to have ya, $G brotha:sista;.$B$BVol''jin makes us all proud in dese moments. It feels good ta be tacklin'' threats head on.' WHERE `Id`=25035;
UPDATE `quest_template` SET `OfferRewardText`='Well fought, young $r.' WHERE `Id`=24812;
UPDATE `quest_template` SET `OfferRewardText`='Excellent work, $N. You''ve turned out to be quite an asset to this garrison. It''s time for you to train!' WHERE `Id`=28774;
UPDATE `quest_template` SET `OfferRewardText`='Get yourself squared away, learn the layout of the land, and come back to me whenever you need training. I''ll be here night or day.$B$BThe Knights of the Silver Hand have done well in making this place fairly safe, but as you meet the other citizens, I think you''ll find they all have problems they could use some help with--help a warrior can give them. Good luck.' WHERE `Id`=3100;
UPDATE `quest_template` SET `OfferRewardText`='You''re a quick learner, $N. Return to me as you grow stronger and I''ll show you other combat techniques.' WHERE `Id`=26913;
UPDATE `quest_template` SET `OfferRewardText`='It''s true, we were ambushed. I don''t dare send any more soldiers out there and risk losing them too. I need a volunteer. Someone willing to risk their life!' WHERE `Id`=28789;
UPDATE `quest_template` SET `OfferRewardText`='I think you now understand the power of the Light. The Light giveth hope, $g brother:sister; and the Light taketh from the darkness! BLESSED BE THE LIGHT!' WHERE `Id`=28813;
UPDATE `quest_template` SET `OfferRewardText`='That will teach those monsters! They''ll think twice before taking another mercenary job for orcs.' WHERE `Id`=28797;
UPDATE `quest_template` SET `OfferRewardText`='With your help we have managed to secure the northern and western sectors of Northshire. We still have a rather large contingency of Blackrock orcs to the east and they''ve begun burning down the forest!' WHERE `Id`=28823;
UPDATE `quest_template` SET `OfferRewardText`='A crate for Goldshire, eh?  People sure are getting lazy. Have you been to Goldshire before?  If so, then it''s no problem, my friend.  I have plenty of gryphons trained to fly that route!' WHERE `Id`=26395;
UPDATE `quest_template` SET `OfferRewardText`='Great, you brought the armor!  We''ll get this divvied to those who need it immediately.$B$BThank you, $N.  Your efforts have been a great help to us.  And now that you''re no stranger to gryphons, I hope you''ll come and lend your aid to Goldshire often!' WHERE `Id`=26396;
UPDATE `quest_template` SET `OfferRewardText`='Thanks for the dust, $N.  Here''s your cash, and...here is a token from associates of mine.  You might find it useful...useful.' WHERE `Id`=47;
UPDATE `quest_template` SET `OfferRewardText`='Yes, I spoke with Remy.  I respect him as a merchant, though all reports of Murlocs to the east have been sketchy at best.$B$BYour concerns are noted, but unless I receive a military report of a murloc threat, we can''t afford to send more troops east.' WHERE `Id`=40;
UPDATE `quest_template` SET `OfferRewardText`='This is bad news.  What''s next, dragons?!?  We''ll have to increase our patrols near that mine.  Thanks for your efforts, $N.  And hold a moment... I might have another task for you.' WHERE `Id`=62;
UPDATE `quest_template` SET `OfferRewardText`='Yes, murlocs have settled in and around the streams of eastern Elwynn.  We don''t know why they are here, but they are aggressive and at least semi-intelligent.' WHERE `Id`=35;
UPDATE `quest_template` SET `OfferRewardText`='You were busy hunting kobolds, were you?  Thanks for the candles, $N, and here''s your reward...' WHERE `Id`=60;
UPDATE `quest_template` SET `RequestItemsText`='You have what??  Maybell is the light of my dull life.  Hurry, let me see her letter!' WHERE `Id`=106;
UPDATE `quest_template` SET `RequestItemsText`='Did you see her yet?  Did you get her?' WHERE `Id`=88;
UPDATE `quest_template` SET `RequestItemsText`='I don''t think it''s right feeding the boy who stole my necklace in the first place, but if that''s what it takes to get back what''s mine, then so be it!$B$BDo you have that boar meat?' WHERE `Id`=86;
UPDATE `quest_template` SET `RequestItemsText`='You have a note from \"Gramma\" Stonefield, eh?  I haven''t seen Mildred in years!  I wonder what she has to say...' WHERE `Id`=107;
UPDATE `quest_template` SET `RequestItemsText`='Do you have that crystal kelp?  I''m sure Maybell is anxious to see her beau...' WHERE `Id`=112;
UPDATE `quest_template` SET `RequestItemsText`='Ugh... I''m starving!  Do you have that pie for me, $N?' WHERE `Id`=84;
UPDATE `quest_template` SET `RequestItemsText`='Did you deliver my letter to Tommy Joe?  What did he say??' WHERE `Id`=114;
UPDATE `quest_template` SET `RequestItemsText`='Hello, $N.  Have you found my necklace?' WHERE `Id`=87;
UPDATE `quest_template` SET `RequestItemsText`='I''m running low on linen, $N.  Do you have any for me?' WHERE `Id`=83;
UPDATE `quest_template` SET `RequestItemsText`='That deadline isn''t getting any further away, $c. Please hurry and collect those bundles of wood.' WHERE `Id`=5545;
UPDATE `quest_template` SET `RequestItemsText`='Turning in a bounty?' WHERE `Id`=26152;
UPDATE `quest_template` SET `RequestItemsText`='What?!?  We haven''t had our people working the Elwynn mines for months!$B$BLet me see that note you have...' WHERE `Id`=123;
UPDATE `quest_template` SET `RequestItemsText`='Hail, $N.  Have you been killing Gnolls...?' WHERE `Id`=11;
UPDATE `quest_template` SET `RequestItemsText`='We don''t need any civilian vigilante types getting involved, kid. Leave this one to the professionals.' WHERE `Id`=184;
UPDATE `quest_template` SET `RequestItemsText`='Hello, $N.  Have you discovered the fates of Rolf and Malakai?' WHERE `Id`=71;
UPDATE `quest_template` SET `RequestItemsText`='I have been commissioned by the Stormwind Army to supply their people with cloth and leather armor.$B$BIf you have a marker for me, then I''d be happy to make you something.' WHERE `Id`=59;
UPDATE `quest_template` SET `RequestItemsText`='You come all the way from Stormwind?  I hear it''s getting dicey down there in the human lands, with brigands and orcs running about.  A perfect place for a $c to prove his worth!' WHERE `Id`=353;
UPDATE `quest_template` SET `RequestItemsText`='Did you find the Collector?  Did you discover whom he''s working for?' WHERE `Id`=147;
UPDATE `quest_template` SET `RequestItemsText`='Greetings and welcome, $gmaster:madam;.  Have you yet tried one of our fine wines?' WHERE `Id`=332;
UPDATE `quest_template` SET `RequestItemsText`='What is it then, $N?' WHERE `Id`=24930;
UPDATE `quest_template` SET `RequestItemsText`='There aren''t many of us left, $N.  We have to look out for those remaining Gilneans.' WHERE `Id`=14395;
UPDATE `quest_template` SET `RequestItemsText`='Did the bait work?' WHERE `Id`=26420;
UPDATE `quest_template` SET `RequestItemsText`='Were you able to find the Confectioners'' Sugar?' WHERE `Id`=26192;
UPDATE `quest_template` SET `RequestItemsText`='Dirt pies don''t make themselves - usually.' WHERE `Id`=26230;
UPDATE `quest_template` SET `RequestItemsText`='You have your orders, $N.' WHERE `Id`=27996;
UPDATE `quest_template` SET `RequestItemsText`='If Taragaman is dead, show me his heart.' WHERE `Id`=26858;
UPDATE `quest_template` SET `RequestItemsText`='Is it done, $N?' WHERE `Id`=24920;
UPDATE `quest_template` SET `RequestItemsText`='Their pride kept them in Auberdine for this long, but none deserve such a cruel fate.' WHERE `Id`=13518;
UPDATE `quest_template` SET `RequestItemsText`='I doubt dey too much of a challenge, mon, but they''ll still claw up ya ankles if ya don''t stay quick footed.' WHERE `Id`=24767;
UPDATE `quest_template` SET `RequestItemsText`='You need to get somewhere fast?  Then you''re talking to the right orc!' WHERE `Id`=6365;
UPDATE `quest_template` SET `RequestItemsText`='I hate quilboar!' WHERE `Id`=25190;
UPDATE `quest_template` SET `RequestItemsText`='Something smells good!  You don''t have raw meat on you, do you?' WHERE `Id`=6384;
UPDATE `quest_template` SET `RequestItemsText`='Have you returned from Orgrimmar?  Did Gryshka like the meat I sent her?' WHERE `Id`=6386;
UPDATE `quest_template` SET `RequestItemsText`='Don''t be too harsh with our captive, he will still need his head attached to answer our questions.' WHERE `Id`=13961;
UPDATE `quest_template` SET `RequestItemsText`='You''ve arrived, and none too soon, $N. Welcome to Shadowglen.$B$BI trust my sigil found you in good spirits and health?$B$BAs I said previously, I am here to train you as a hunter; to tame beasts to aid you in battle; to use a bow with unerring accuracy; to respect the lands which we call home and also the lands beyond.' WHERE `Id`=3117;
UPDATE `quest_template` SET `RequestItemsText`='This is grim work. It pains me to have to inflict such violence on creature of the forest, corrupt or not.' WHERE `Id`=28726;
UPDATE `quest_template` SET `RequestItemsText`='I adore these forests. I want to see the corruption purged from them completely. When next I return, I wand to do so with a lighter heart.' WHERE `Id`=28727;
UPDATE `quest_template` SET `RequestItemsText`='Did you have any success in routing those grellkin for us?' WHERE `Id`=13946;
UPDATE `quest_template` SET `RequestItemsText`='Are their numbers weakened?' WHERE `Id`=13945;
UPDATE `quest_template` SET `RequestItemsText`='The road is still not safe, $c. Travel forth and slay the Gnarlpine ambushers and return to me.' WHERE `Id`=487;
UPDATE `quest_template` SET `RequestItemsText`='Do you have the seeds?  I am eager to plant them.' WHERE `Id`=918;
UPDATE `quest_template` SET `RequestItemsText`='Hello, $N.  Have you found any sprouts near the waters?' WHERE `Id`=919;
UPDATE `quest_template` SET `RequestItemsText`='Did you find the source of the corruption?' WHERE `Id`=14005;
UPDATE `quest_template` SET `RequestItemsText`='Cut off the head of their leader, and chaos ensues, $N. Learn this lesson well. It will aid you in the future.' WHERE `Id`=872;
UPDATE `quest_template` SET `RequestItemsText`='Mok''ra, stranger. Are you here from Far Watch?' WHERE `Id`=13949;
UPDATE `quest_template` SET `RequestItemsText`='Was that you I saw waving a gun around from the back of my last caravan?' WHERE `Id`=13975;
UPDATE `quest_template` SET `RequestItemsText`='Da naga have been our enemies for a long, long time, and our previous encounters with dem have not gone well. It be clear dat dis time will be different. Tings have changed, and you be part of dat change.' WHERE `Id`=24625;
UPDATE `quest_template` SET `RequestItemsText`='Destroy those humans, $n.' WHERE `Id`=25169;
UPDATE `quest_template` SET `RequestItemsText`='Ah, you got my letter, $N... good.$B$BThere''s been an influx of warriors in Elwynn recently--which is good for Stormwind, but bad for the orcs in the area.' WHERE `Id`=3100;
UPDATE `quest_template` SET `RequestItemsText`='Is that sweat on your brow, $glad:ma''am;?  You''ve been running too much.  Next time, take a gryphon!' WHERE `Id`=26395;
UPDATE `quest_template` SET `RequestItemsText`='You''re back from Stormwind?  Did Osric send the armor?' WHERE `Id`=26396;
UPDATE `quest_template` SET `RequestItemsText`='Is it done yet, $N?' WHERE `Id`=14204;
UPDATE `quest_template` SET `RequestItemsText`='Psst!  You have that Gold Dust for me...for me?' WHERE `Id`=47;
UPDATE `quest_template` SET `RequestItemsText`='Do you have it all, $N? I can''t wait to see it on you!$B$BYou bought the good stuff, right?' WHERE `Id`=14109;